name: musclex
channels:
  - conda-forge
dependencies:
  - python=3.12 # pin to avoid pyvista issues
  - fenics-dolfinx>=0.10.0
  - adios4dolfinx
  - mpich
  - pyvista
  - meshio
  - pygmsh
  - ipython
  - pyyaml
  - matplotlib<3.11.0 # scienceplots compatibility
  - scienceplots
  - scipy
  - seaborn
  - typer
  - adios2
  - imageio
  - imageio-ffmpeg
  - salib
  - tqdm
  - pip
  - pip:
    - -e . 
