# Run script as:
# snakemake -s scripts/figure3.smk --cores 1 --use-conda

from pathlib import Path

# --- Global Configuration ---
ROOT_DIR = Path(workflow.basedir).parent
RESULTS_DIR = ROOT_DIR / "results"
CONFIG_DIR = ROOT_DIR / "config_files"
SCRIPT_DIR = Path("__file__").parent
PAPER_FIG_DIR = RESULTS_DIR / "paperfigures"

PROTOCOLS = ["defreitas", "weekly", "everythreedays"]


rule all:
    input:
        PAPER_FIG_DIR / "figure3.svg",


# --- Simulation Rule 1: Baseline ODEs ---
rule runThreeProtocols:
    output:
        expand(
            RESULTS_DIR / "paper/figure3/{protocol}/ode_results.csv",
            protocol=PROTOCOLS,
        ),
    input:
        config=CONFIG_DIR / "exercise_eq.yml",
    params:
        protocols=PROTOCOLS,
    conda:
        "musclex"
    script:
        SCRIPT_DIR / "run_three_protocols_baselineODE.py"


# --- Simulation Rule 2: Myofibril Comparison ---
rule runMyofibrilComparison:
    output:
        expand(
            RESULTS_DIR / "paper/figure3e/{protocol}/ode_results.csv",
            protocol=PROTOCOLS,
        ),
    input:
        config=CONFIG_DIR / "exercise_eq_reduced_k1.yml",
    params:
        protocols=PROTOCOLS,
    conda:
        "musclex"
    script:
        SCRIPT_DIR / "run_myofibril_comparison.py"


# --- Final Figure Generation Rule ---
# This rule collects all the CSV data and generates the final composite figure.
rule generateFigure3:
    input:
        # It now depends on all the generated CSVs.
        protocol_results=rules.runThreeProtocols.output,
        myofibril_results=rules.runMyofibrilComparison.output,
        # The SA results are a static input, not generated by a rule.
        sa_results=RESULTS_DIR / "SA/sensitivity_analysis_parallel_N=10000_order=2/ST.csv",
        baseline_config=CONFIG_DIR / "exercise_eq.yml",
    output:
        PAPER_FIG_DIR / "figure3.svg",
    params:
        protocols=PROTOCOLS,
    conda:
        "musclex"
    script:
        # The final script that does all the plotting.
        SCRIPT_DIR / "generate_figure3.py"
