from pathlib import Path
from typing import List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scienceplots
import typer
from matplotlib import rc

# Matplotlib styling
plt.style.use("science")
plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = ["Arial"]
plt.rcParams["font.size"] = 7
plt.rcParams["svg.fonttype"] = "none"

rc("text", usetex=False)


app = typer.Typer()


@app.command()
def main(
    csv_files: List[Path] = typer.Argument(
        ...,
        help="One or more paths to the growth_results.csv files.",
    ),
    labels: str = typer.Option(
        ...,
        "--labels",
        help="Pipe-separated list of legend labels.",
        rich_help_panel="Input/Output",
    ),
    output_file: Path = typer.Option(
        ...,
        "--output-file",
        help="Path to save the output PNG figure.",
        rich_help_panel="Input/Output",
    ),
):
    """
    Generates a 2-panel figure comparing CSA and Volume over time
    for different simulation cases.
    """
    # Split the pipe-separated labels generated by Snakemake
    label_list = labels.split("|")

    if len(csv_files) != len(label_list):
        print("Warning: The number of CSV files does not match the number of labels.")

    # --- Plotting Setup ---
    fig, axes = plt.subplots(1, 2, figsize=(4, 1.5))

    # Generate a unique color for each individual case (CSV file)
    colors = plt.cm.viridis(np.linspace(0, 0.9, len(csv_files)))

    # Define linestyles to cycle through
    linestyles = ["-", "--", ":", "-."]

    # --- Process and Plot Data ---
    for i, csv_file in enumerate(csv_files):
        df = pd.read_csv(csv_file)

        # Normalize CSA and Volume by their initial values
        csa_norm = df["csa"] / df["csa"].iloc[0]
        volume_norm = df["volume"] / df["volume"].iloc[0]

        time_weeks = df["t"] / (24 * 7)

        # Assign label and line style
        current_label = label_list[i] if i < len(label_list) else f"Case {i}"
        current_ls = linestyles[i % len(linestyles)]

        # Plot normalized CSA
        axes[0].plot(
            time_weeks, csa_norm, ls=current_ls, color=colors[i], label=current_label
        )

        # Plot normalized Volume
        axes[1].plot(time_weeks, volume_norm, ls=current_ls, color=colors[i])

    # --- Final Figure Formatting ---
    # Set y labels for each subplot
    axes[0].set_ylabel("Normalized CSA")
    axes[1].set_ylabel("Normalized Volume")

    # Common settings for all subplots
    for ax in axes:
        ax.set_xlabel("Time (weeks)")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(top=False, right=False)
        ax.minorticks_off()

    # Get handles and labels from the first plot to create a single legend
    handles, labels_from_plot = axes[0].get_legend_handles_labels()

    # Place the legend to the right of the subplots
    fig.legend(handles, labels_from_plot, loc="center left", bbox_to_anchor=(1.0, 0.5))

    # Adjust subplot layout to make room for the legend
    plt.tight_layout()

    # Save the figures (using bbox_inches='tight' prevents legend cutoff)
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.savefig(output_file.with_suffix(".svg"), bbox_inches="tight")
    print(f"Convergence figure saved to: {output_file}")


if __name__ == "__main__":
    app()
